// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewyqozozuluyfnemgsuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3eXFvem96dWx1eWZuZW1nc3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDMzODMsImV4cCI6MjA3Mjg3OTM4M30.8kwXyPJpc0FMrW72PwTqJxkE0gA9Na1xH_ax4_aSEBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});